worker_processes  1;

events {
    worker_connections  1024;
}

rtmp {
    server {
        listen 1935; # Porta para o seu C# enviar o vídeo
        chunk_size 1024;

        application live {
            live on;
            record all;                         # Grava tudo (áudio e vídeo)
            record_path temp/recordings;        # Pasta onde os vídeos serão salvos
            record_unique on;                   # Adiciona um sufixo de tempo (evita sobrescrever)
            record_suffix _%d%m%Y_%H%M%S.flv;   # Formato: dia_mes_ano_hora_min_seg

            # Configuração para assistir no Navegador (HTML5)
            hls on;
            hls_path temp/hls;
            hls_fragment 6;
            hls_playlist_length 120;
        }
    }
}


# Se for usar HTML5, precisa desse servidor HTTP para ler o .m3u8
http {
    server {
        listen 8080;
        location /hls {
            types {
                application/vnd.apple.mpegurl m3u8;
            }
            root temp;
            add_header Cache-Control no-cache;
            add_header Access-Control-Allow-Origin *; # Permite rodar no seu site
        }
    }
}